# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: draw.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='draw.proto',
  package='',
  serialized_pb='\n\ndraw.proto\"\x18\n\tDrawQuery\x12\x0b\n\x03uid\x18\x01 \x02(\t\"L\n\x08\x44rawResp\x12\x0e\n\x06result\x18\x01 \x02(\x05\x12\x0e\n\x06reward\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\t\x12\x11\n\tleftTimes\x18\x04 \x01(\x05')




_DRAWQUERY = _descriptor.Descriptor(
  name='DrawQuery',
  full_name='DrawQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='DrawQuery.uid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=14,
  serialized_end=38,
)


_DRAWRESP = _descriptor.Descriptor(
  name='DrawResp',
  full_name='DrawResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='DrawResp.result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reward', full_name='DrawResp.reward', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='DrawResp.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leftTimes', full_name='DrawResp.leftTimes', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['DrawQuery'] = _DRAWQUERY
DESCRIPTOR.message_types_by_name['DrawResp'] = _DRAWRESP

class DrawQuery(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DRAWQUERY

  # @@protoc_insertion_point(class_scope:DrawQuery)

class DrawResp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DRAWRESP

  # @@protoc_insertion_point(class_scope:DrawResp)


# @@protoc_insertion_point(module_scope)
